version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mysundayimages
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mysundayimages .
      - docker tag mysundayimages:latest $REPOSITORY_URI:latest
      - docker tag mysundayimages:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Saving Docker image as tar file...
      - docker save -o mysundayimages.tar mysundayimages:latest
artifacts:
  files:
    - my-sample-appimages.tar
  discard-paths: yes
  base-directory: ./
  name: docker-images/my-sample-appimages.tar