version: 0.2

env:
  variables:
    REPOSITORY_URI: 339713006307.dkr.ecr.us-east-1.amazonaws.com/sample-springboot
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 15; done"
      - echo check docker version installed.......
      - docker version
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - cd springboot-sample
      - mvn clean package
      - mvn checkstyle:check
      - mvn test
      - echo "All tests completed"
      - echo "Building the Docker image..."
      - docker build -t sample-springboot .
      - docker tag sample-springboot:latest $REPOSITORY_URI:latest
      - docker tag sample-springboot:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.jar
  discard-paths: yes
  base-directory: springboot-sample
