version: 0.2

env:
  variables:
    REPOSITORY_URI: 339713006307.dkr.ecr.us-east-1.amazonaws.com/sample-springboot
    AWS_DEFAULT_REGION: us-east-1

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - yum update -y
      - yum install -y docker
      - service docker start
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - cd springboot-sample
      - mvn clean package
      - mvn checkstyle:check
      - mvn test
      - echo "All tests completed"
      - echo "Building the Docker image..."
      - docker build -t sample-springboot .
      - docker tag sample-springboot:latest $REPOSITORY_URI:latest
      - docker tag sample-springboot:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.jar
  discard-paths: yes
  base-directory: springboot-sample